refactor(vue-tutorial): move Meteor tutorial to vue3
meteor/vue-tutorial pull request #23
Opened 2023-07-14 03:35 UTC by vit0rr

Hi!!
This PR is dedicated to refactoring every vue-tutorial to vue3. I'll also include a tutorial about prettier and eslint to vue get autosuggestion at IDE. Also, use Vue router, tailwindcss, and the newest version from MeteorJS.

And also using composition.
Issue ref.: https://github.com/meteor/vue-tutorial/issues/20

#### Code
- [ ] step01
- [ ] step02
- [ ] step03
- [ ] step04
- [ ] step05
- [ ] step06
- [ ] step07
- [ ] step08
- [ ] step09
- [ ] step10
- [ ] step11
- [ ] step12

#### Documentation (markdown)
- [ ] step01
- [ ] step02
- [ ] step03
- [ ] step04
- [ ] step05
- [ ] step06
- [ ] step07
- [ ] step08
- [ ] step09
- [ ] step10
- [ ] step11
- [ ] step12
- [ ] step13

2023-08-01 19:37 UTC, Grubba27 commented on tutorial/simple-todos/01-creating-app.md
> +meteor npm install --save-dev eslint eslint-plugin-vue eslint-config-prettier eslint-plugin-prettier
could this be one big command?
and plugin PHP is really necessary?

```suggestion

meteor npm install --save-dev eslint eslint-plugin-vue eslint-config-prettier eslint-plugin-prettier prettier @prettier/plugin-php

```

2023-08-01 19:41 UTC, Grubba27 commented on tutorial/simple-todos/01-creating-app.md
> +meteor create --vue simple-todos-vue --prototype
later on you ask the user to add autopublish package, you should either pass the `--prototype` or ask the user to add the autopublish package

2023-08-01 19:43 UTC, Grubba27 commented on tutorial/simple-todos/01-creating-app.md
> +meteor create --vue simple-todos-vue --prototype
https://github.com/meteor/meteor/blob/cb6c97dc5f9897b61a5479d415a61ae2b61d1fac/tools/cli/commands.js#L1054-L1062

2023-08-01 20:10 UTC, Grubba27 requested changes
I would like to see those changes before this becomes a new tutorial. And recommend asking @henriquealbert and @fredmaiaarantes for review in this PR as well

2023-08-02 18:16 UTC, henriquealbert requested changes
I would remove the prototype part from the tutorial and also separate in 2 tutorials: vue2 and vue3

2023-08-02 18:17 UTC, Grubba27 commented on tutorial/simple-todos/01-creating-app.md
> +meteor create --vue simple-todos-vue --prototype
I think we could change this
Maybe removing this `--prototype` and later on asking the user for the autopublish and other package that you have already mentioned

2023-08-02 18:19 UTC, Grubba27 commented on tutorial/simple-todos/01-creating-app.md
> +meteor create --vue simple-todos-vue --prototype
Asking the user to add `autopublish` and `insecure` sounds good

2023-08-11 19:11 UTC, vit0rr commented
I think that we can close this PR since it is moved to https://github.com/meteor/vue3-tutorial/pull/2

2023-08-11 19:11 UTC, closed without merging